version: '3'

services:
    metrics:
        volumes:
            # code to be analysed, i.e., </your/local/php/project>:/project
            - ~/Sites/webforms/app:/project
        working_dir: /project
        build: .
    web:
        image: nginx:latest
        ports:
            - "8088:80"
        volumes:
            # show report, i.e., </your/local/php/project/_metrics/>:/code
            - ~/Sites/webforms/app/_metrics/:/code
            - ./site.conf:/etc/nginx/conf.d/default.conf